spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
  datasource:
    #jdbc:postgresql://10.43.140.79:5432/postgres
    url: jdbc:postgresql://${DATABASE_URL:host.docker.internal}:5432/postgres
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:admin}
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: none
      show-sql: true

    properties:
      hibernate:
        format_sql: true

